version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/catdamnit
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
  - location: /scripts/cleanup.sh
    runas: ubuntu
  ApplicationStart:
  - location: /scripts/restart.sh
    runas: ubuntu
  ApplicationStop:
  - location: /scripts/stop.sh
    runas: ubuntu