version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/catdamnit
permissions:
  - object: /
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
  - location: scripts/cleanup.sh